[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
rand = "0.8.5"
winit = { version = "0.29.15", features = ["rwh_05"] }
winit_input_helper = "0.16.0"